### ISSUE TITLE
feature: add molly as a dev dependency of the project

### ISSUE THREAD

**Issue by opensas** [renefournier/molly#1]
so we can

```
npm install -d lilmolly
```
and then create a script to run it, like `npm run check:unused`

**Comment by renefournier** [comment]
Great idea! Will do. This is my first semi-legitimate open source effort. For the sake of experience, could you write a PR that does this to the repo?

**Comment by renefournier** [comment]
Added and updated docs https://github.com/renefournier/molly/commit/1083319c7161ba6150635bd2dbc2e3da1d3c7d4a
