### ISSUE TITLE
The script throws an error on startup

### ISSUE THREAD

**Issue by Serator** [renefournier/molly#2]
![image](https://github.com/renefournier/molly/assets/625005/380ba106-0c0b-4414-a017-b4a6d8119053)

Steps to reproduce the issue:
* `npm install --save-dev lilmolly`
* Add script `"check:unused": "lilmolly"` to package.json
* `npm run check:unused`

Software versions:
* Windows v10
* Node.js v18.16.0
* Lilmolly v1.2.8

**Comment by renefournier** [comment]
Oh I see you are on Windows without WSL! OK, I'm working on making it Windows-compatible. Stay tuned.

**Comment by renefournier** [comment]
Closed with https://github.com/renefournier/molly/commit/5afddc09ae2463b6ac616d9c73939f7e6f3f2a2a

**Comment by Serator** [comment]
@renefournier Thanks for the super quick fix. 🚀 But I still have a problem, possibly unrelated to this error.

![image](https://github.com/renefournier/molly/assets/625005/ef4347a8-56fc-4365-9cf0-92e2fe42eea3)

The script highlighted all the `lib/**/*.svelte` files. This may be due to the fact that I keep each component in a separate directory.

**Comment by renefournier** [comment]
Hmm, that _shouldn't_ matter. Can you please share me the entire textual output of your terminal window? I'm on macOS, so my hand-waving is in the dark.

**Comment by renefournier** [comment]
Oh I think I get it, it may be that the filenames themselves are all index.svelte?

**Comment by Serator** [comment]
> Hmm, that shouldn't matter. Can you please share me the entire textual output of your terminal window? I'm on macOS, so my hand-waving is in the dark.

A long list of files and after that:
![image](https://github.com/renefournier/molly/assets/625005/18719ae4-482f-4a13-af70-2a32ab403d9c)

> Oh I think I get it, it may be that the filenames themselves are all index.svelte?

Yeah, all the files are `index.svelte`. The name of the component in the parent `index.svelte` directory. I use this to place assets next to the component code and not mix them with other components.

**Comment by renefournier** [comment]
I thought this was a Windows problem, and maybe it is, but I'm not sure how to handle cases where `index.svelte` is used instead of a unique (at least for the directory) filename like `/src/lib/Projects/Project/Slider.svelte`. I will have to think on it.

**Comment by renefournier** [comment]
Fixed in https://github.com/renefournier/molly/commit/601fc31247e64836185f4471f7bdb6a8c1836b76 and earlier commits
