### ISSUE TITLE
Support for Advanced routing

### ISSUE THREAD

**Issue by dskelton-cos** [renefournier/molly#3]
Hi,  

I ran it on my project in Stackblitz, but my project is using advanced routing folders.
https://kit.svelte.dev/docs/advanced-routing#advanced-layouts

And marked almost all of the components as unused. 

This was just a quick test after I heard about it, but I will try again in a default sk project. without advanced routing.

Cheers
David

**Comment by renefournier** [comment]
Someone handled in https://github.com/renefournier/molly/commit/963b4c13bc0d7b1f2176b8fe3b400ae1c76f132d
