### ISSUE TITLE
Support for aliases imports

### ISSUE THREAD

**Issue by buhodev** [renefournier/molly#4]
Thank you so much for this project! I ran the command on my sveltekit project and lilmolly wrongly marked some components as unused. I think that the reason might be because I'm using [aliases](https://kit.svelte.dev/docs/configuration#alias), but I'm not sure :)

OS: Windows 11

**Comment by notkimroberts** [comment]
I'm commenting to report the same issue with aliases.

**Comment by renefournier** [comment]
Thanks for the feedback. I will look into it and the other issue.

**Comment by OllieJT** [comment]
I'm not sure if there's a straightforward way to resolve a path alias reliably, however a half-measure I believe could be impactful is supporting the svelte-kit default alias's.

$src = /src
$lib = /src/lib

With that said, though aliasing can be handled in several ways with typescript, the colloquial method recommended in the svelte-kit docs manages aliases via `svelte.config.js` file. I believe Molly could reliably access these by importing the config like so...

```js
import fs from 'fs';
import path from 'path';

function read_svelte_config() {
	// Construct the path to svelte.config.js in the consumer's project root
	const configPath = path.join(process.cwd(), 'svelte.config.js');

	try {
		// Check if the file exists
		if (fs.existsSync(configPath)) {
			// Read the file
			const content = fs.readFileSync(configPath, 'utf8');

			/** @type {import('@sveltejs/kit').Config} */
			const config = JSON.parse(content);

			return config;
		} else {
			console.error(`svelte.config.js does not exist at: ${configPath}`);
			return null;
		}
	} catch (err) {
		console.error(`Error reading svelte.config.js: ${err.message}`);
		return null;
	}
}

const svelte_config = read_svelte_config();

const consumer_alias = svelte_config?.kit?.alias || {};
// consumer_alias: { $src: 'src', $lib: 'src/lib' }

```

I don't use jsdoc much, so apologies for my iffy types.

**Comment by OllieJT** [comment]
Forgot to tag you @renefournier, hope this helps. I might jump in with a contrib if I have time but this is all I could manage right now.

Nice work!

**Comment by renefournier** [comment]
Hi @OllieJT , if you have a `contrib` that would be great. I've fixed a different thing yesterday, one thing I think from your code sample (which looks great) is only that the `svelte.config.js` is not JSON, so perhaps no need to `JSON.parse()` it. But the idea is really good. Let’s try for this.

**Comment by renefournier** [comment]
Handled in https://github.com/renefournier/molly/commit/963b4c13bc0d7b1f2176b8fe3b400ae1c76f132d.

**Comment by OllieJT** [comment]
Nice work!
